'use client';
import Link from 'next/link';
import {usePathname} from "next/navigation";

export default function RootLayout({ children }) {
    return (
        <div className="flex h-screen flex-col md:flex-row md:overflow-hidden">
            <div className="w-full flex-none md:w-64">

            </div>
            <div className="flex-grow p-6 md:overflow-y-auto md:p-12">{children}</div>
        </div>
    );
}

// import { Inter } from "next/font/google";
// import "./globals.css";
//
// const inter = Inter({ subsets: ["latin"] });
//
// export const metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };
//
// export default function RootLayout({ children }) {
//     return (
//         <html lang="en">
//         <body className={inter.className}>{children}</body>
//         </html>
//     );
// }
